// [[Rcpp::depends(lidR)]]
// [[Rcpp::depends(RcppArmadillo)]]
// [[Rcpp::plugins(openmp)]]

#include <RcppArmadillo.h>
#include <SpatialIndex.h>
#include <Rcpp.h>
#include <queue>
#include <utility>
#include <vector>

#ifdef _OPENMP
  #include <omp.h>
#endif

using namespace Rcpp;
using namespace lidR;



//' helper function to unlist IDs generated by dbscan::frNN
//'
//'
//' creates a vector of indices from a nested list created by dbscan::frNN
//'
//' @param list a list element created by dbscan::frNN
//' @param l the expected length of the result
//' @return Returns a vector with the values in the list.
//' @author Julian Frey <julian.frey@@iww.uni-freiburg.de>
//' @export fast_unlist
// [[Rcpp::export]]
IntegerVector fast_unlist(List list, int l){

  // define results
  IntegerVector res(l);

  int k = 0;
  for (int i = 0; i < list.length(); ++i) {
    for (int j = 0; j < as<IntegerVector>(list[i]).length(); j++){
      res[k] = i;
      k++;
    }
  }

  // return indices
  return res;
}

//' helper function to unlist distances computed by dbscan::frNN
//'
//' extracts the distances from a nested list created by dbscan::frNN
//'
//' @param list a list element created by dbscan::frNN
//' @param l the expected length of the result
//' @return Returns a vector with the values in the list.
//' @author Julian Frey <julian.frey@@iww.uni-freiburg.de>
//' @export fast_unlist_dist
// [[Rcpp::export]]
NumericVector fast_unlist_dist(List list, int l){

  // define results
  NumericVector res(l);

  int k = 0;
  for (int i = 0; i < list.length(); ++i) {
    NumericVector dists = as<NumericVector>(list[i]);
    for (int j = 0; j < dists.length(); j++){
      res[k] = dists[j];
      k++;
    }
  }

  // return indices
  return res;
}


//' Fast Eigenvalues decomposition for k nearest neighbors using a C++ function
//'
//' C++ helper function to compute eigenvalues for geometric feature
//' calculation.
//'
//' @param las LAS element
//' @param k k nearest neighbors
//' @param ncpu number of cpu cores to use
//' @return The function returns for every point the 3 eigenvalues and the
//' third element of the third eigenvector. These values are needed to compute
//' planarity, linerity, verticality etc. in the add_geometry function
//' @author Julian Frey <julian.frey@@iww.uni-freiburg.de>
//' @seealso \link{add_geometry}
//' @export eigen_decomposition
// [[Rcpp::export]]
NumericMatrix eigen_decomposition(S4 las, int k, int ncpu = 1)
{
  DataFrame data = as<DataFrame>(las.slot("data"));
  NumericVector X = data["X"];
  NumericVector Y = data["Y"];
  NumericVector Z = data["Z"];
  unsigned int npoints = X.size();

  NumericMatrix out(npoints, 4);

  SpatialIndex index(las);

#ifdef _OPENMP
  #pragma omp parallel for num_threads(ncpu)
#endif
  for (unsigned int i = 0 ; i < npoints ; i++)
  {
    arma::mat A(k,3);
    arma::mat coeff;  // Principle component matrix
    arma::mat score;
    arma::vec latent; // Eigenvalues in descending order

    PointXYZ p(X[i], Y[i], Z[i]);

    std::vector<PointXYZ> pts;
    index.knn(p, k, pts);

    for (unsigned int j = 0 ; j < pts.size() ; j++)
    {
      A(j,0) = pts[j].x;
      A(j,1) = pts[j].y;
      A(j,2) = pts[j].z;
    }

    arma::princomp(coeff, score, latent, A);

#ifdef _OPENMP
  #pragma omp critical
#endif

{
  out(i, 0) = latent[0];
  out(i, 1) = latent[1];
  out(i, 2) = latent[2];
  out(i, 3) = coeff[8];
}
  }

  return out;
}

//' Point distance function
//'
//' calculates euclidean distances for n dimensions between a matrix of points and a single point
//'
//' @param mat matrix with points as rows
//' @param p point to calculate distances
//' @param nthreads number of threads to use. If 0 or negative, the maximum number of threads available will be used.
//'
//' @return the distances between every row of mat and p
//' @export p_mat_dist
//'
//' @examples
//' p_mat_dist(as.matrix(cbind(runif(100),runif(100))), c(3,4))
// [[Rcpp::export]]
Rcpp::NumericVector p_mat_dist(Rcpp::NumericMatrix mat,
                               Rcpp::NumericVector p,
                               int nthreads = 0) {

  int n = mat.nrow();
  int d = mat.ncol();

  if (p.size() != d) {
    Rcpp::stop("Length of p must match number of columns of mat.");
  }
  if (nthreads < 1) {
    #ifdef _OPENMP
  nthreads = omp_get_max_threads();
  #else
    nthreads = 1;
  #endif
  }
  Rcpp::NumericVector out(n);

  #ifdef _OPENMP
    #pragma omp parallel for num_threads(nthreads)
  #endif
  for (int i = 0; i < n; i++) {

    double sum_sq = 0.0;

    for (int j = 0; j < d; j++) {
      double diff = mat(i, j) - p[j];
      sum_sq += diff * diff;
    }

    out[i] = std::sqrt(sum_sq);
  }

  return out;
}

// [[Rcpp::export]]
Rcpp::List multi_source_dijkstra(IntegerVector from,
                                 IntegerVector to,
                                 NumericVector weight,
                                 int n_vertices,
                                 IntegerVector seeds) {
  if (from.size() != to.size() || from.size() != weight.size()) {
    stop("from, to, and weight must have the same length.");
  }
  if (n_vertices < 1) {
    stop("n_vertices must be positive.");
  }

  std::vector<std::vector<std::pair<int, double>>> adjacency(n_vertices);
  for (R_xlen_t edge = 0; edge < from.size(); ++edge) {
    const int u = from[edge] - 1;
    const int v = to[edge] - 1;
    const double w = weight[edge];
    if (u < 0 || u >= n_vertices || v < 0 || v >= n_vertices) {
      stop("Edge endpoints must be between 1 and n_vertices.");
    }
    if (!R_finite(w) || w < 0.0) {
      stop("Edge weights must be finite and non-negative.");
    }
    adjacency[u].push_back(std::make_pair(v, w));
    adjacency[v].push_back(std::make_pair(u, w));
  }

  typedef std::pair<double, int> DistanceLabel;
  typedef std::pair<DistanceLabel, int> QueueEntry;
  std::priority_queue<QueueEntry,
                      std::vector<QueueEntry>,
                      std::greater<QueueEntry>> queue;
  std::vector<double> distance(n_vertices, R_PosInf);
  std::vector<int> label(n_vertices, NA_INTEGER);

  for (R_xlen_t seed_index = 0; seed_index < seeds.size(); ++seed_index) {
    const int vertex = seeds[seed_index] - 1;
    if (vertex < 0 || vertex >= n_vertices) {
      stop("Seeds must be between 1 and n_vertices.");
    }
    const int candidate_label = seed_index + 1;
    if (distance[vertex] > 0.0 ||
        (distance[vertex] == 0.0 &&
         (label[vertex] == NA_INTEGER || candidate_label < label[vertex]))) {
      distance[vertex] = 0.0;
      label[vertex] = candidate_label;
      queue.push(std::make_pair(std::make_pair(0.0, candidate_label), vertex));
    }
  }

  while (!queue.empty()) {
    const QueueEntry current = queue.top();
    queue.pop();
    const double current_distance = current.first.first;
    const int current_label = current.first.second;
    const int vertex = current.second;
    if (current_distance != distance[vertex] || current_label != label[vertex]) {
      continue;
    }
    for (const auto& neighbor : adjacency[vertex]) {
      const int next_vertex = neighbor.first;
      const double candidate_distance = current_distance + neighbor.second;
      if (candidate_distance < distance[next_vertex] ||
          (candidate_distance == distance[next_vertex] &&
           (label[next_vertex] == NA_INTEGER || current_label < label[next_vertex]))) {
        distance[next_vertex] = candidate_distance;
        label[next_vertex] = current_label;
        queue.push(std::make_pair(std::make_pair(candidate_distance, current_label), next_vertex));
      }
    }
  }

  return List::create(
    _["distance"] = wrap(distance),
    _["seed_index"] = wrap(label)
  );
}