# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_unlist <- function(list, l) {
    .Call(`_CspStandSegmentation_fast_unlist`, list, l)
}

fast_unlist_dist <- function(list, l) {
    .Call(`_CspStandSegmentation_fast_unlist_dist`, list, l)
}

eigen_decomposition <- function(las, k, ncpu = 1L) {
    .Call(`_CspStandSegmentation_eigen_decomposition`, las, k, ncpu)
}

