# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' helper function to unlist IDs generated by dbscan::frNN
#'
#'
#' creates a vector of indices from a nested list created by dbscan::frNN
#'
#' @param list a list element created by dbscan::frNN
#' @param l the expected length of the result
#' @return Returns a vector with the values in the list.
#' @author Julian Frey <julian.frey@@iww.uni-freiburg.de>
#' @export fast_unlist
fast_unlist <- function(list, l) {
    .Call(`_CspStandSegmentation_fast_unlist`, list, l)
}

#' helper function to unlist distances computed by dbscan::frNN
#'
#' extracts the distances from a nested list created by dbscan::frNN
#'
#' @param list a list element created by dbscan::frNN
#' @param l the expected length of the result
#' @return Returns a vector with the values in the list.
#' @author Julian Frey <julian.frey@@iww.uni-freiburg.de>
#' @export fast_unlist_dist
fast_unlist_dist <- function(list, l) {
    .Call(`_CspStandSegmentation_fast_unlist_dist`, list, l)
}

#' Fast Eigenvalues decomposition for k nearest neighbors using a C++ function
#'
#' C++ helper function to compute eigenvalues for geometric feature
#' calculation.
#'
#' @param las LAS element
#' @param k k nearest neighbors
#' @param ncpu number of cpu cores to use
#' @return The function returns for every point the 3 eigenvalues and the
#' third element of the third eigenvector. These values are needed to compute
#' planarity, linerity, verticality etc. in the add_geometry function
#' @author Julian Frey <julian.frey@@iww.uni-freiburg.de>
#' @seealso \link{add_geometry}
#' @export eigen_decomposition
eigen_decomposition <- function(las, k, ncpu = 1L) {
    .Call(`_CspStandSegmentation_eigen_decomposition`, las, k, ncpu)
}

#' Point distance function
#'
#' calculates euclidean distances for n dimensions between a matrix of points and a single point
#'
#' @param mat matrix with points as rows
#' @param p point to calculate distances
#' @param nthreads number of threads to use. If 0 or negative, the maximum number of threads available will be used.
#'
#' @return the distances between every row of mat and p
#' @export p_mat_dist
#'
#' @examples
#' p_mat_dist(as.matrix(cbind(runif(100),runif(100))), c(3,4))
p_mat_dist <- function(mat, p, nthreads = 0L) {
    .Call(`_CspStandSegmentation_p_mat_dist`, mat, p, nthreads)
}

#' Multi-source Dijkstra shortest paths
#'
#' Computes shortest-path distances from several source vertices simultaneously
#' on an undirected graph with finite, non-negative edge weights. Each vertex
#' is assigned to the source with the smallest path cost. Ties are resolved in
#' favour of the earliest source in `seeds`. Unreachable vertices have an
#' infinite distance and `NA` source index.
#'
#' @param from Integer vector of one-based origin vertex indices.
#' @param to Integer vector of one-based destination vertex indices. Must have
#'   the same length as `from`.
#' @param weight Numeric vector of finite, non-negative edge weights. Must have
#'   the same length as `from` and `to`.
#' @param n_vertices Total number of vertices, including isolated vertices.
#' @param seeds Integer vector of one-based source vertex indices. The returned
#'   `seed_index` refers to positions in this vector rather than vertex IDs.
#'
#' @return A list with `distance`, a numeric vector of shortest-path costs, and
#'   `seed_index`, an integer vector identifying the closest source for each
#'   vertex.
#'
#' @details The graph is treated as undirected: every input edge is available in
#' both directions. The algorithm has time complexity
#' \eqn{O((V + E) \log V)} and stores one distance and source label per vertex.
#' It is therefore suitable for nearest-source assignment without materializing
#' a source-by-vertex distance matrix.
#'
#' @export
multi_source_dijkstra <- function(from, to, weight, n_vertices, seeds) {
    .Call(`_CspStandSegmentation_multi_source_dijkstra`, from, to, weight, n_vertices, seeds)
}

